spring.application.name=incident-service

spring.datasource.url=${AEGISOPS_DB_URL:jdbc:mysql://localhost:3307/aegisops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${AEGISOPS_DB_USERNAME:aegisops}
spring.datasource.password=${AEGISOPS_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true